apiVersion: build.tanzu.vmware.com/v1
kind: ContainerAppBuildPlan
metadata:
  name: simple.tanzu.vmware.com
  namespace: default
spec:
  buildpacks:
    builder: paketobuildpacks/builder-jammy-base
  postBuildSteps:
  - containerTask:
      image: alpine
      command: ["/bin/sh","-c"]
      args:
        - |
          env ;
          ls -l
  registry: ""
  runtimes: []